#!/bin/bash
#dtime: count difference in numbers between last two lines of file

case $# in
0) getsec; awk '{line[NR] = $0}\
END { dt = line[NR] - line[NR-1];\
     hr  = dt / 3600.;\
     min = (dt / 60) % 60 ;\
     sec = dt % 60.;\
     {printf "%d sec %.0d:%.0d:%02d\n",  dt,hr,min,sec}\
}' /tmp/time.junk ;; #no args: use tmp

*)  awk '{line[NR] = $0}\
END { dt = line[NR] - line[NR-1];\
     hr  = dt / 3600.;\
     min = (dt / 60) % 60 ;\
     sec = dt % 60.;\
     {printf "%d sec %.0d:%.0d:%02d\n",  dt,hr,min,sec}\
}' $1 ;; # 1 arg: read file given
esac
