#!/bin/bash
CASE=`pwd`

# CHECK IF CASE IS HR
isHR=$1

if [[ $isHR = "1" ]]; then
  FILEC="monitor_cell_195349.dat"
  FILE1="monitor_cell_323547.dat"
  FILE2="monitor_cell_99837.dat"
  FILEBL="monitor_cell_268786.dat"
  FILE3="monitor_cell_25854.dat"
  FILE4="monitor_cell_363792.dat"
else
  FILEC="monitor_cell_343345.dat"
  FILE1="monitor_cell_196864.dat"
  FILE2="monitor_cell_88658.dat"
  FILEBL="monitor_cell_244242.dat"
  FILE3="monitor_cell_25961.dat"
  FILE4="monitor_cell_333215.dat"
fi

#set terminal png
#set output ofilename
LOC="Corner-3"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILE3}" every ::3 using 1:6 w l
EOFMarker

LOC="Backleg"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILEBL}" every ::3 using 1:6 w l
EOFMarker

LOC="Corner-2"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILE2}" every ::3 using 1:6 w l
EOFMarker

LOC="Corner-4"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILE4}" every ::3 using 1:6 w l
EOFMarker

LOC="Collector"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILEC}" every ::3 using 1:6 w l
EOFMarker

LOC="Corner-1"
gnuplot -persist <<-EOFMarker
  set title "$CASE  $LOC" font ",12"
  set term png
  unset key
  set xlabel "Time (s)"
  set ylabel "Pressure (Pa)"
  set format y "%.1f"
  set output "${CASE}/plot-${LOC}.png"
  plot "${CASE}/${FILE1}" every ::3 using 1:6 w l
EOFMarker

