#!/bin/bash
#
# pmore: find what percent higher x is than y
# pmore < x > < y >
#echo $1:10:23:24 |\
echo $* |\
awk  -F' ' '{{x = $1;\
              y = $2;\
              p =  (x/y - 1 ) * 100.;\
              printf "%.1f\n",p}}'
