#!/usr/bin/python
import sys, getopt

def main(argv):
  inputfile = ''
  outputfile = ''
  try:
    opts, args = getopt.getopt(argv, "h:i:o:",["ifile=","ofile"])
  except getopt.GetoptError:
    print 'test.py -i <inputfile> -o <outputfile>'
    sys.exit(2)
  for opt, arg in opts:
    if opt == '-h':
      print 'test.py -i <inputfile> -o <outputfile>'
      sys.exit()
    elif opt in ("-i", "--ifile"):
      inputfile = arg
    elif opt in ("-o", "--ofile"):
      outputfile = arg
  print 'Input  file is ', inputfile
  print 'output file is ', outputfile

if __name__ == "__main__":
  main(sys.argv[1:])



'''
v = 1.0

#while True:
while v > 0:
  v = input('give seconds: ')
  print '%f seconds == %f minutes ' % (v, v/60.)
'''


