#!/bin/bash
#for i in $( ls | grep '.*png'); do
#for i in $( ls | grep '.*3\.[0-3]000.*'); do

##for i in $( ls | grep 'Vx.*1.4'); do
#function myF1 {
#  str=a:b:c:d:e
#  IFS=:
#  ary=($str)
#  for key in "${!ary[@]}"; do
#    echo "$key ${ary[$key]}";
#  done
#}
#
#myF1


function changeNames {
for i in $( ls | grep '.*png'); do
   dt=$( echo $i | rev | cut -d _ -f 1 | rev | sed 's/.png//g' | cut -d e -f 2)
   name=$( echo $i | rev | cut -d _ -f 2- | rev )
   num=$( echo $i | rev | cut -d _ -f 1 | rev )

   #special treatment for e-02
   if [ "$dt" = "-03" ]; then
     #dt="-00"
     dt="A"
   fi
   if [ "$dt" = "-02" ]; then
     #dt="-00"
     dt="B"
   fi
   if [ "$dt" = "-01" ]; then
     #dt="-00"
     dt="C"
   fi
   if [ "$dt" = "+00" ]; then
     #dt="-00"
     dt="D"
   fi

   # change name
   newName=$( echo "$name"_e"$dt"_"$num" )
   #echo $newName dt = $dt
   mv $i $newName &
 done
}

function changeBack {
for i in $( ls | grep '.*png'); do
   newName=$( echo $i | sed 's/_e.*_/_/g' )

   # change name back
   #echo $newName
   mv $i $newName &
 done
}





if [ "$1" = "1" ]; then
    echo changing back
    changeBack
else
    echo changing Names
    changeNames
fi
